###############################################################################
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 23-05-2023
#   LICENSE: GPLv3.0
#
###############################################################################
---
name: CI

on: push

jobs:

  s0:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: efcomp-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Exec make
        shell: bash -l {0}
        run: make s0

  s1:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: efcomp-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Exec make
        shell: bash -l {0}
        run: make s1

  s2:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: efcomp-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Exec make
        shell: bash -l {0}
        run: make s2

  s3:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: efcomp-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Exec make
        shell: bash -l {0}
        run: make s3

  s4:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: efcomp-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Exec make
        shell: bash -l {0}
        run: make s4

  s5:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: efcomp-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Exec make
        shell: bash -l {0}
        run: make s5

  docker:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t efcomp:latest -f Dockerfile .

      # non-interactive shell needs to initialise & activate conda in a different way than -it
      #
      # Dockerception is not advised (running Docker in a Docker, dind)
      # https://stackoverflow.com/a/33003273/2340598
      #
      # ~AngryMaciek
      #- name: make help
      #  run: |
      #    docker run --name efcomp -v /home/runner/work/efcomp/efcomp:/efcomp efcomp /bin/bash -c "source /mambaforge/etc/profile.d/conda.sh && conda activate efcomp-dev && make"
      #    docker rm efcomp
      #
      # Dockerception is not advised (running Docker in a Docker, dind)
      # https://stackoverflow.com/a/33003273/2340598

...
