###############################################################################
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 23-05-2023
#   LICENSE: GPLv3.0
#
###############################################################################
---
name: CI

on: push

jobs:

  session_0:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./session/0_SystemSetup
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
...
